
from django.urls import path
from .import views

urlpatterns = [
  path('Login/',views.login_get),
  path('Login_post/',views.login_post),
  path('adminhome/',views.adminhome),
  path('petshophome/',views.petshophome),
  path('Changepass/',views.changepass_get),
  path('Changepass_post/',views.changepass_post),
  path('Addpetshop/',views.addpetshop_get),
  path('Addpetshop_post/',views.addpetshop_post),
  path('Viewpetshop/',views.viewpetshop_get),
  path('Viewpetshop_post/',views.viewpetshop_post),
  path('Editpetshop/<id>',views.editpetshop_get),
  path('Editpetshop_post/',views.editpetshop_post),
  path('Deletepetshop/<id>',views.deletepetshop_get),
  path('Adddeliveryboy/',views.adddeliveryboy_get),
  path('Adddeliveryboy_post/',views.adddeliveryboy_post),
  path('adminViewdeliveryboy/',views.adminViewdeliveryboy),
  path('adminViewdeliveryboy_post/',views.Viewdeliveryboy_post),
  path('Editdeliveryboy/<id>',views.editdeliveryboy_get),
  path('Editdeliveryboy_post/',views.editdeliveryboy_post),
  path('Deletedeliveryboy/<id>',views.deletedeliveryboy_get),
  path('Reviewdeliveryboy/',views.reviewdeliveryboy_get),
  path('Reviewdeliveryboy_post/',views.reviewdeliveryboy_post),
  path('assignorder_get_post/',views.assignorder_get_post),
  path('view_assigned_order_get/',views.view_assigned_order_get),

  path('Changepassdb/',views.changepasspetshop_get),
  path('Changepassdb_post/',views.changepasspetshop_post),
  path('Addpet/',views.addpet_get),
  path('Addpet_post/',views.addpet_post),
  path('Editpet/<id>',views.editpet_get),
  path('Editpet_post/',views.editpet_post),
  path('Viewpet/',views.viewpet_get),
  path('Viewpet_post/',views.viewpet_post),
  path('Deletepet/<id>',views.deletepet_get),

  path('addpet_products_get/',views.addpet_products_get),
  path('addpet_products_post/',views.addpet_products_post),
  path('editpet_products_get/<id>',views.editpet_products_get),
  path('editpet_products_post/',views.editpet_products_post),
  path('Viewpetproducts/',views.Viewpetproducts),
  path('Viewpetproducts_post/',views.Viewpetproducts_post),
  path('deletepetproduct_get/<id>',views.deletepetproduct_get),


  path('Adddisease/',views.adddiseasepet_get),
  path('Adddisease_post/',views.adddiseasepet_post),
  path('Editdisease/<id>',views.editdisease_get),
  path('Editdisease_post/',views.editdisease_post),
  path('Viewdisease/', views.viewdisease_get),
  # path('Viewdisease_/', views.viewdisease_get),
  # path('Viewdisease_post/', views.viewdisease_post),
  path('Deletedisease/<id>', views.deletedisease_get),
  path('Deletedisease_post/', views.deletedisease_post),
  # path('Reviewdisease_/', views.reviewdisease_get),
  # path('Reviewdisease_post/', views.reviewdisease_post),

  path('reviewpet_get/<id>',views.reviewpet_get),
  path('Reviewpet_post/',views.reviewpet_post),
  path('Addgrooming/',views.addgrooming_get),
  path('Addgrooming_post/',views.addgrooming_post),
  path('Viewgrooming/', views.viewgrooming_get),
  # path('Viewgrooming_post/', views.viewgrooming_post),
  path('Editgrooming/<id>',views.editgrooming_get),
  path('Editgrooming_post/',views.editgrooming_post),
  path('deletegrooming/<id>',views.deletegrooming_get),

  path('Viewgroomingreq/',views.viewgroomingreq_get),
  path('Viewgroomingreq_post/',views.viewgroomingreq_post),
  path('approvingroomingreq/<id>',views.approvingroomingreq_get),
  path('rejectinggroomingreq/<id>', views.rejectinggroomingreq_get),
  path('viewapprovedgroomingreq/', views.viewapprovedgroomingreq_get),
  path('viewapprovedgroomingreq_post/', views.viewapprovedgroomingreq_post),
  path('viewrejectedgroomingreq/', views.viewrejectedgroomingreq_get),
  path('viewrejectedgroomingreq_post/', views.viewrejectedgroomingreq_post),

  path('Viewdeliveryboy/',views.viewdeliveryboy_get),
  # path('Viewdeliveryboy/<id>',views.viewdeliveryboy_get),
  path('Viewdeliveryboy_post/',views.viewdeliveryboy_post),

  path('Vieworder/',views.vieworder_get),
  path('Vieworder_post/', views.vieworder_post),
  path('Moreorderdetails/<id>', views.moreorderdetails_get),
  path('Moreorderdetails/', views.moreorderdetails_post),

  path('viewpetorder_get/', views.viewpetorder_get),
  path('viewpetorder_post/', views.viewpetorder_post),
  path('moreorderpetdetails_get/<id>', views.moreorderpetdetails_get),
  path('moreorderpetdetails_post/', views.moreorderpetdetails_post),


  path('assignorder_get/<id>', views.assignorder_get),
  path('viewassignorder_get/', views.view_assigned_order_get),
  path('user_sendrating_post/',views.user_sendrating_post),
  path('user_viewrating_post/',views.user_viewrating_post),
  path('flutter_login_get/',views.flutter_login_get),
  path('user_registeration_get/', views.user_registeration_get),
  path('user_view_profile/', views.user_view_profile),
  path('user_editprofile_get/', views.user_editprofile_get),
  path('Flutter_Change_password_get/', views.Flutter_Change_password_get),
  path('flutter_viewpet_get/', views.flutter_viewpet_get),
  path('addtocart_get/', views.addtocart_get),
  # path('sell_and_adopt_get/', views.sell_and_adopt_get),
  path('view_cart_get/', views.view_cart_get),
  path('remove_item_get/', views.remove_item_get),
  path('flutter_viewpetproducts_get/', views.flutter_viewpetproducts_get),
  path('addtocart_products_get/', views.addtocart_products_get),
  path('flutter_viewpetproducts_get/', views.flutter_viewpetproducts_get),
  path('remove_item_product_get/', views.remove_item_product_get),
  path('view_cart_products_get/', views.view_cart_products_get),
  path('user_sell_pet/', views.user_sell_pet),
  path('flutter_viewmypets_get/', views.flutter_viewmypets_get),
  path('flutter_userviewgrooming_get/', views.flutter_userviewgrooming_get),
  path('flutter_usersendreq_get/', views.flutter_usersendreq_get),
  path('flutter_userviewreq_get/', views.flutter_userviewreq_get),
  path('flutter_userviewgroomget/', views.flutter_userviewgroomget),
  path('cartpayment/', views.cartpayment),
  path('user_view_product_cart/', views.user_view_product_cart),
  path('user_view_pets_cart/', views.user_view_pets_cart),
  path('Grooming_payment/', views.Grooming_payment),
  path('view_payments/', views.view_payments),
  path('cartpayment_pet/', views.cartpayment_pet),
  path('del_viewreviewrating/', views.del_viewreviewrating),
  path('del_viewassignedworg/', views.del_viewassignedworg),
  path('del_update_order/', views.del_update_order),
  path('del_view_profile/', views.del_view_profile),
  path('view_nearby_vets/', views.view_nearby_vets),
  path('add_nearby_vets_get/', views.add_nearby_vets_get),
  path('add_nearby_vets_post/', views.add_nearby_vets_post),
  path('pet_disease_prediction/', views.pet_disease_prediction),
  path('chat/<id>', views.chat1),
  path('chat_view/', views.chat_view),
  path('chat_send/<msg>', views.chat_send),
  path('User_sendchat/', views.User_sendchat),
  path('User_viewchat/', views.User_viewchat),
  path('forgot_pass/', views.forget_password_post),
  path('generate_gemini_response/', views.generate_gemini_response),
  path('chatbot/', views.chat),
  path('user_view_orders/', views.user_view_orders),
  path('deletepet_flutt/', views.deletepet_flutt),







]

